version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    day: friday
    interval: weekly
    time: "05:30"
    timezone: Europe/London
  reviewers:
    - "martincostello"
#- package-ecosystem: nuget
#  directory: "/"
#  groups:
#    xunit:
#      patterns:
#        - xunit*
#  schedule:
#    day: friday
#    interval: weekly
#    time: "05:30"
#    timezone: Europe/London
#  reviewers:
#    - "martincostello"
#  open-pull-requests-limit: 99
- package-ecosystem: npm
  directory: "/src/TodoApp"
  groups:
    babel:
      patterns:
        - "@babel/*"
    typescript-eslint:
      patterns:
        - "@typescript-eslint/*"
  schedule:
    day: friday
    interval: weekly
    time: "05:30"
    timezone: Europe/London
  reviewers:
    - "martincostello"
  open-pull-requests-limit: 99
